name: Automatic Release

on:
  push:
    branches:
      - base
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  automatic-release:
    uses: RockefellerArchiveCenter/.github/.github/workflows/pythonpublish.yml@base
